### PR TITLE
fix issue

### PR DESCRIPTION
**Pull request by Qewertyy**
https://github.com/ItsCEED/Imaginepy/issues/7

### CODE REVIEW

**Comment by elricsilverhandx** [comment]
```
HEADERS = {
        "accept": "*/*",
        "user-agent": "okhttp/4.10.0",
        "style-id":"30"
    }
```

**Comment by Qewertyy** [comment]
> ```
> HEADERS = {
>         "accept": "*/*",
>         "user-agent": "okhttp/4.10.0",
>         "style-id":"30"
>     }
> ```

varies from model to model

**Comment by elricsilverhandx** [comment]
> > ```
> > HEADERS = {
> >         "accept": "*/*",
> >         "user-agent": "okhttp/4.10.0",
> >         "style-id":"30"
> >     }
> > ```
> 
> varies from model to model

I agree, but there is a way to prevent this.

The addition you made with another bot does not work. It works with the code addition I made.

**Comment by Qewertyy** [comment]
> 

its works if you know what you are doing

**Comment by raymerjacque** [comment]
https://github.com/ItsCEED/Imaginepy/issues/7#issuecomment-1602453060

I actually made a nice little GUI, which worked up until a few days ago when this issue started...  Anyone that can help me modify this python script to make it work ?  feel free to use if it we can fix it, its pretty nice. as it shows previews of image on the gui. i created it the day before all this happened... so barely had enough time to enjoy image generation when everything went dark. but it was working nicely.

```
import os
import sys
import random
import string
import threading
from tkinter import *
from tkinter import ttk
from tkinter import filedialog
from tkinter import messagebox
from tkinter import ttk
from PIL import Image, ImageTk
from imaginepy import Imagine, Style, Ratio
from imaginepy import Imagine

class MyImagine(Imagine):
    def __init__(self):
        super().__init__()
        self.__api = "https://inferenceengine.vyro.ai"

class ImageGenerator:
    def __init__(self, root):

        # Spinner settings
        self.spinner_frames = ["|", "/", "-", "\\"]
        self.spinner_index = 0

        styles = [
            "ABSTRACT_CITYSCAPE", "ABSTRACT_VIBRANT", "AMAZONIAN", "ANIME", "ANIME_V2", "ARCHITECTURE", "AVATAR",
            "CANDYLAND", "CLAYMATION", "CINEMATIC_RENDER", "COMIC_BOOK", "COMIC_V2",
            "COSMIC", "CUBISM", "DISNEY", "DYSTOPIAN", "ELVEN", "EUPHORIC", "EXTRA_TERRESTRIAL", "FANTASY", "FIREBENDER",
            "FORESTPUNK", "FUTURISTIC", "GLASS_ART", "GHOTIC", "GRAFFITI", "GTA", "HAUNTED", "ICON", "ILLUSTRATION",
            "IMAGINE_V1", "IMAGINE_V3", "IMAGINE_V4_Beta", "INTERIOR", "JAPANESE_ART", "KAWAII_CHIBI", "KNOLLING_CASE",
            "LANDSCAPE", "LOGO", "MACRO_PHOTOGRAPHY", "MARBLE", "MEDIEVAL", "MINECRAFT", "MYSTICAL", "NEO_FAUVISM", 
            "NEON", "ORIGAMI", "PAINTING", "PALETTE_KNIFE", "PAPERCUT_STYLE", "PICASO", "PIXEL_ART", 
            "POLAROID", "POLY_ART", "POP_ART", "PORTRAIT", "POSTER_ART", "PRODUCT_PHOTOGRAPHY", 
            "PSYCHEDELIC", "RAINBOW", "REALISTIC", "RENDER", "RENAISSANCE", "RETRO", "RETROWAVE", "ROCOCCO",
            "SAMURAI", "SCATTER", "SHAMROCK_FANTASY", "SKETCH", "STAINED_GLASS", "STICKER", "STUDIO_GHIBLI", 
            "SURREALISM", "V4_CREATIVE", "VAN_GOGH", "VIBRANT", "VIBRAN_VIKING", "WATERBENDER", "WOOLITIZE"
        ]

        ratios = [
            "RATIO_1X1", "RATIO_2X3", "RATIO_3X1", "RATIO_3X2", "RATIO_3X4", "RATIO_4X3", "RATIO_4X5",
            "RATIO_5X4", "RATIO_9X16", "RATIO_16X9"
        ]

        self.root = root
        self.root.title("Image Generator")
        self.root.geometry("800x600")
    
        # disable resizing the GUI
        self.root.resizable(False, False)

        # disable the maximize button
        if sys.platform.startswith('win'):  # if the operating system is windows
            self.root.attributes('-fullscreen', False)  
        else:  # for linux and mac
            self.root.attributes('-zoomed', False)


        style = ttk.Style()
        style.theme_use("clam")  

        Label(self.root, text="Prompt:").grid(row=0, column=0, columnspan=2)
        self.prompt_entry = Entry(self.root, width=50, font=('Arial', 14))
        self.prompt_entry.insert(0, "random")
        self.prompt_entry.grid(row=1, column=0, columnspan=2)

        Label(self.root, text="Style:").grid(row=2, column=0)
        self.style_combo = ttk.Combobox(self.root, values=styles, width=50)
        self.style_combo.set("ANIME_V2")  # set default style
        self.style_combo.grid(row=3, column=0)

        Label(self.root, text="Ratio:").grid(row=2, column=1)
        self.ratio_combo = ttk.Combobox(self.root, values=ratios, width=50)
        self.ratio_combo.set("RATIO_16X9")  # set default ratio
        self.ratio_combo.grid(row=3, column=1)

        self.generate_button = Button(self.root, text="Generate Image", command=self.generate_image_threaded, width=20, height=2)
        self.generate_button.grid(row=4, column=0, columnspan=2, pady=10)

        self.canvas = Canvas(self.root, width=800, height=600)
        self.canvas.grid(row=5, column=0, columnspan=2)
        self.canvas.bind("<Button-1>", self.open_image) 

        self.last_image_path = None

    def generate_image_threaded(self):
       threading.Thread(target=self.generate_image).start()
       self.generating_window = Toplevel(self.root)
       self.generating_window.title("Generating image...")
       self.generating_window.geometry("350x130") # Increase size of the window
       # Create a label for the spinner
       self.spinner_label = Label(self.generating_window, text="Generating image, please wait...\n\n" + self.spinner_frames[0], font=('Arial', 16))
       self.spinner_label.pack()

       self.update_spinner() # Start the spinner

       # Only attempt to get the window dimensions if the window exists
       if self.generating_window.winfo_exists():
           self.generating_window.update()  # needed to get accurate window dimensions

           # Get the root window's position and dimensions
           root_x = self.root.winfo_rootx()
           root_y = self.root.winfo_rooty()
           root_width = self.root.winfo_width()
           root_height = self.root.winfo_height()

           # Get the popup window's dimensions
           window_width = self.generating_window.winfo_width()
           window_height = self.generating_window.winfo_height()

           # Compute the position where the popup window should be
           position_top = root_y + root_height // 2 - window_height // 2
           position_left = root_x + root_width // 2 - window_width // 2

           # Position the window
           self.generating_window.geometry(f"+{position_left}+{position_top}")

    def update_spinner(self):
        # Check if generating_window exists
        if self.generating_window.winfo_exists():
            self.spinner_index = (self.spinner_index + 1) % len(self.spinner_frames)
            self.spinner_label["text"] = "Generating image, please wait...\n\n" + self.spinner_frames[self.spinner_index]

            # Schedule the next frame
            self.root.after(100, self.update_spinner)

    def generate_image(self):
        self.generate_button.config(state="disabled")

        prompt = self.prompt_entry.get()
        style = getattr(Style, self.style_combo.get())
        ratio = getattr(Ratio, self.ratio_combo.get())

        imagine = MyImagine()

        try:
            img_data = imagine(prompt=prompt, style=style, ratio=ratio)
        except:
            messagebox.showerror("Error", "Error generating image, hit generate again.")
            self.cleanup()
            return

        if img_data is None:
            messagebox.showerror("Error", "An error occurred while generating the image.")
            self.cleanup()
            return

        img_data = imagine.upscale(image=img_data)

        if img_data is None:
            messagebox.showerror("Error", "An error occurred while upscaling the image.")
            self.cleanup()
            return

        prefix = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
        image_filename = f"images/{prefix}_image.png"

        with open(image_filename, mode="wb") as img_file:
            img_file.write(img_data)

        self.last_image_path = image_filename  

        self.load_image(image_filename)
        self.cleanup()

    def load_image(self, img_path):
        img = Image.open(img_path)
        img.thumbnail((800, 600))
        self.photo = ImageTk.PhotoImage(img)
        self.canvas.create_image(0, 0, image=self.photo, anchor=NW)

    def cleanup(self):
        self.generate_button.config(state="normal")
        self.generating_window.destroy()

    def open_image(self, event):
        if self.last_image_path is not None:
            os.system(f'start "" "{self.last_image_path}"')


if __name__ == "__main__":
    os.makedirs("images", exist_ok=True)

    root = Tk()
    app = ImageGenerator(root)
    root.mainloop()
```
    
    ####################
    
    I have tried everything to make it work... no luck. whatever they changed has broken the script completely.

**Comment by ItsCEED** [comment]
Can you please update the non-async version also?

@Qewertyy

**Comment by Qewertyy** [comment]
> Can you please update the non-async version also?
> 
> @Qewertyy

sure.

**Comment by Qewertyy** [comment]
> [#7 (comment)](https://github.com/ItsCEED/Imaginepy/issues/7#issuecomment-1602453060)
> 
> I actually made a nice little GUI, which worked up until a few days ago when this issue started... Anyone that can help me modify this python script to make it work ? feel free to use if it we can fix it, its pretty nice. as it shows previews of image on the gui. i created it the day before all this happened... so barely had enough time to enjoy image generation when everything went dark. but it was working nicely.
> 
> ```
> import os
> import sys
> import random
> import string
> import threading
> from tkinter import *
> from tkinter import ttk
> from tkinter import filedialog
> from tkinter import messagebox
> from tkinter import ttk
> from PIL import Image, ImageTk
> from imaginepy import Imagine, Style, Ratio
> from imaginepy import Imagine
> 
> class MyImagine(Imagine):
>     def __init__(self):
>         super().__init__()
>         self.__api = "https://inferenceengine.vyro.ai"
> 
> class ImageGenerator:
>     def __init__(self, root):
> 
>         # Spinner settings
>         self.spinner_frames = ["|", "/", "-", "\\"]
>         self.spinner_index = 0
> 
>         styles = [
>             "ABSTRACT_CITYSCAPE", "ABSTRACT_VIBRANT", "AMAZONIAN", "ANIME", "ANIME_V2", "ARCHITECTURE", "AVATAR",
>             "CANDYLAND", "CLAYMATION", "CINEMATIC_RENDER", "COMIC_BOOK", "COMIC_V2",
>             "COSMIC", "CUBISM", "DISNEY", "DYSTOPIAN", "ELVEN", "EUPHORIC", "EXTRA_TERRESTRIAL", "FANTASY", "FIREBENDER",
>             "FORESTPUNK", "FUTURISTIC", "GLASS_ART", "GHOTIC", "GRAFFITI", "GTA", "HAUNTED", "ICON", "ILLUSTRATION",
>             "IMAGINE_V1", "IMAGINE_V3", "IMAGINE_V4_Beta", "INTERIOR", "JAPANESE_ART", "KAWAII_CHIBI", "KNOLLING_CASE",
>             "LANDSCAPE", "LOGO", "MACRO_PHOTOGRAPHY", "MARBLE", "MEDIEVAL", "MINECRAFT", "MYSTICAL", "NEO_FAUVISM", 
>             "NEON", "ORIGAMI", "PAINTING", "PALETTE_KNIFE", "PAPERCUT_STYLE", "PICASO", "PIXEL_ART", 
>             "POLAROID", "POLY_ART", "POP_ART", "PORTRAIT", "POSTER_ART", "PRODUCT_PHOTOGRAPHY", 
>             "PSYCHEDELIC", "RAINBOW", "REALISTIC", "RENDER", "RENAISSANCE", "RETRO", "RETROWAVE", "ROCOCCO",
>             "SAMURAI", "SCATTER", "SHAMROCK_FANTASY", "SKETCH", "STAINED_GLASS", "STICKER", "STUDIO_GHIBLI", 
>             "SURREALISM", "V4_CREATIVE", "VAN_GOGH", "VIBRANT", "VIBRAN_VIKING", "WATERBENDER", "WOOLITIZE"
>         ]
> 
>         ratios = [
>             "RATIO_1X1", "RATIO_2X3", "RATIO_3X1", "RATIO_3X2", "RATIO_3X4", "RATIO_4X3", "RATIO_4X5",
>             "RATIO_5X4", "RATIO_9X16", "RATIO_16X9"
>         ]
> 
>         self.root = root
>         self.root.title("Image Generator")
>         self.root.geometry("800x600")
>     
>         # disable resizing the GUI
>         self.root.resizable(False, False)
> 
>         # disable the maximize button
>         if sys.platform.startswith('win'):  # if the operating system is windows
>             self.root.attributes('-fullscreen', False)  
>         else:  # for linux and mac
>             self.root.attributes('-zoomed', False)
> 
> 
>         style = ttk.Style()
>         style.theme_use("clam")  
> 
>         Label(self.root, text="Prompt:").grid(row=0, column=0, columnspan=2)
>         self.prompt_entry = Entry(self.root, width=50, font=('Arial', 14))
>         self.prompt_entry.insert(0, "random")
>         self.prompt_entry.grid(row=1, column=0, columnspan=2)
> 
>         Label(self.root, text="Style:").grid(row=2, column=0)
>         self.style_combo = ttk.Combobox(self.root, values=styles, width=50)
>         self.style_combo.set("ANIME_V2")  # set default style
>         self.style_combo.grid(row=3, column=0)
> 
>         Label(self.root, text="Ratio:").grid(row=2, column=1)
>         self.ratio_combo = ttk.Combobox(self.root, values=ratios, width=50)
>         self.ratio_combo.set("RATIO_16X9")  # set default ratio
>         self.ratio_combo.grid(row=3, column=1)
> 
>         self.generate_button = Button(self.root, text="Generate Image", command=self.generate_image_threaded, width=20, height=2)
>         self.generate_button.grid(row=4, column=0, columnspan=2, pady=10)
> 
>         self.canvas = Canvas(self.root, width=800, height=600)
>         self.canvas.grid(row=5, column=0, columnspan=2)
>         self.canvas.bind("<Button-1>", self.open_image) 
> 
>         self.last_image_path = None
> 
>     def generate_image_threaded(self):
>        threading.Thread(target=self.generate_image).start()
>        self.generating_window = Toplevel(self.root)
>        self.generating_window.title("Generating image...")
>        self.generating_window.geometry("350x130") # Increase size of the window
>        # Create a label for the spinner
>        self.spinner_label = Label(self.generating_window, text="Generating image, please wait...\n\n" + self.spinner_frames[0], font=('Arial', 16))
>        self.spinner_label.pack()
> 
>        self.update_spinner() # Start the spinner
> 
>        # Only attempt to get the window dimensions if the window exists
>        if self.generating_window.winfo_exists():
>            self.generating_window.update()  # needed to get accurate window dimensions
> 
>            # Get the root window's position and dimensions
>            root_x = self.root.winfo_rootx()
>            root_y = self.root.winfo_rooty()
>            root_width = self.root.winfo_width()
>            root_height = self.root.winfo_height()
> 
>            # Get the popup window's dimensions
>            window_width = self.generating_window.winfo_width()
>            window_height = self.generating_window.winfo_height()
> 
>            # Compute the position where the popup window should be
>            position_top = root_y + root_height // 2 - window_height // 2
>            position_left = root_x + root_width // 2 - window_width // 2
> 
>            # Position the window
>            self.generating_window.geometry(f"+{position_left}+{position_top}")
> 
>     def update_spinner(self):
>         # Check if generating_window exists
>         if self.generating_window.winfo_exists():
>             self.spinner_index = (self.spinner_index + 1) % len(self.spinner_frames)
>             self.spinner_label["text"] = "Generating image, please wait...\n\n" + self.spinner_frames[self.spinner_index]
> 
>             # Schedule the next frame
>             self.root.after(100, self.update_spinner)
> 
>     def generate_image(self):
>         self.generate_button.config(state="disabled")
> 
>         prompt = self.prompt_entry.get()
>         style = getattr(Style, self.style_combo.get())
>         ratio = getattr(Ratio, self.ratio_combo.get())
> 
>         imagine = MyImagine()
> 
>         try:
>             img_data = imagine(prompt=prompt, style=style, ratio=ratio)
>         except:
>             messagebox.showerror("Error", "Error generating image, hit generate again.")
>             self.cleanup()
>             return
> 
>         if img_data is None:
>             messagebox.showerror("Error", "An error occurred while generating the image.")
>             self.cleanup()
>             return
> 
>         img_data = imagine.upscale(image=img_data)
> 
>         if img_data is None:
>             messagebox.showerror("Error", "An error occurred while upscaling the image.")
>             self.cleanup()
>             return
> 
>         prefix = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
>         image_filename = f"images/{prefix}_image.png"
> 
>         with open(image_filename, mode="wb") as img_file:
>             img_file.write(img_data)
> 
>         self.last_image_path = image_filename  
> 
>         self.load_image(image_filename)
>         self.cleanup()
> 
>     def load_image(self, img_path):
>         img = Image.open(img_path)
>         img.thumbnail((800, 600))
>         self.photo = ImageTk.PhotoImage(img)
>         self.canvas.create_image(0, 0, image=self.photo, anchor=NW)
> 
>     def cleanup(self):
>         self.generate_button.config(state="normal")
>         self.generating_window.destroy()
> 
>     def open_image(self, event):
>         if self.last_image_path is not None:
>             os.system(f'start "" "{self.last_image_path}"')
> 
> 
> if __name__ == "__main__":
>     os.makedirs("images", exist_ok=True)
> 
>     root = Tk()
>     app = ImageGenerator(root)
>     root.mainloop()
> ```
> 
> ```
> ####################
> 
> I have tried everything to make it work... no luck. whatever they changed has broken the script completely.
> ```

update the package after he merges the pull request

**Pull request closed without merging**
